-- Better Auth schema (identity + sessions for "Sign in with Grok").
--
-- Generated by the Better Auth CLI for its Postgres adapter — DO NOT EDIT by
-- hand. `@/lib/auth/server` runs Better Auth against these tables when
-- DATABASE_URL is set. The columns are camelCase and MUST stay double-quoted so
-- Postgres preserves the case Better Auth queries by.
--
-- Migrations in this folder are the single source of truth for your schema. They
-- apply to Neon during the Vercel build (`npm run build`) and to the local
-- PGLite fallback automatically on startup, so dev matches production. Applied
-- files are recorded by name in `_migrations` and NEVER run again.
--
-- Put YOUR app's schema in NEW ordered files (0002_*.sql, 0003_*.sql, …), never
-- in this one. For app tables, prefer snake_case and give per-user tables a
-- `user_id TEXT NOT NULL` column (TEXT, not UUID — the preview dev user id is
-- the string 'dev-user'), then scope every query to the authenticated user
-- server-side (see the `neon` + `auth` skills and src/lib/auth/verify.server.ts).

create table if not exists "user" (
  "id" text not null primary key,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" boolean not null,
  "image" text,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create table if not exists "session" (
  "id" text not null primary key,
  "expiresAt" timestamptz not null,
  "token" text not null unique,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user" ("id") on delete cascade
);

create table if not exists "account" (
  "id" text not null primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user" ("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope" text,
  "password" text,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz not null
);

create table if not exists "verification" (
  "id" text not null primary key,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create index if not exists "session_userId_idx" on "session" ("userId");
create index if not exists "account_userId_idx" on "account" ("userId");
create index if not exists "verification_identifier_idx" on "verification" ("identifier");

-- Painite Marketplace member profiles and invite codes.

create table if not exists permission_codes (
  code       text primary key,
  created_at timestamptz not null default now()
);

insert into permission_codes (code)
values ('PAINITE11')
on conflict (code) do nothing;

create table if not exists profiles (
  user_id         text primary key,
  name            text not null,
  phone           text not null unique,
  permission_code text not null,
  created_at      timestamptz not null default now()
);

create unique index if not exists profiles_phone_idx on profiles (phone);

-- Admin console + single-use permission codes.

alter table permission_codes
  add column if not exists used_at timestamptz,
  add column if not exists used_by text;

create table if not exists admin_settings (
  id            integer primary key,
  password_hash text not null,
  password_salt text not null,
  updated_at    timestamptz not null default now()
);

create table if not exists admin_sessions (
  token_hash text primary key,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

-- Member avatars and isolated Facebook profiles.

alter table profiles
  add column if not exists avatar text;

create table if not exists facebook_profiles (
  id             text primary key,
  user_id        text not null,
  label          text not null,
  proxy_host     text,
  proxy_port     integer,
  proxy_username text,
  proxy_password text,
  created_at     timestamptz not null default now()
);

create index if not exists facebook_profiles_user_idx on facebook_profiles (user_id);

alter table facebook_profiles
  add column if not exists proxy_protocol text;

alter table facebook_profiles
  add column if not exists serial_no integer;

update facebook_profiles as p
set serial_no = s.rn
from (
  select id, row_number() over (partition by user_id order by created_at desc) as rn
  from facebook_profiles
) as s
where p.id = s.id
  and p.serial_no is null;

create table if not exists rent_posts (
  id         text primary key,
  user_id    text not null,
  serial_no  int not null default 1,
  zpid       text,
  title      text not null,
  address    text,
  price      text,
  beds       text,
  baths      text,
  sqft       text,
  facts      text,
  image_url  text,
  created_at timestamptz not null default now()
);

create index if not exists rent_posts_user_idx on rent_posts (user_id, serial_no);
create unique index if not exists rent_posts_user_zpid_idx on rent_posts (user_id, zpid) where zpid is not null;

create table if not exists leads (
  id           text primary key,
  user_id      text not null,
  member_name  text not null,
  member_phone text not null,
  body         text not null,
  created_at   timestamptz not null default now()
);

create index if not exists leads_user_idx on leads (user_id, created_at desc);

alter table leads add column if not exists source text;
alter table leads add column if not exists listing_url text;
alter table leads add column if not exists property_type text;
alter table leads add column if not exists budget text;
alter table leads add column if not exists status text;
alter table leads add column if not exists contact_name text;
alter table leads add column if not exists contact_phone text;
alter table leads add column if not exists profile_label text;

update leads set status = 'new' where status is null;

alter table admin_settings add column if not exists gemini_key text;

alter table facebook_profiles add column if not exists auto_reply integer not null default 0;
alter table leads add column if not exists fb_name text;
alter table leads add column if not exists fb_link text;

alter table leads add column if not exists inbox_url text;

alter table leads add column if not exists address text;

alter table profiles add column if not exists uid text;
