import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("painiteDesktop", {
  isDesktop: true,
  prepareFacebook: (input) => ipcRenderer.invoke("painite:prepare-session", input),
  showFacebook: (profile) => ipcRenderer.invoke("painite:facebook-show", profile),
  hideFacebook: () => ipcRenderer.invoke("painite:facebook-hide"),
  boundsFacebook: (bounds) => ipcRenderer.invoke("painite:facebook-bounds", bounds),
  reloadFacebook: (profile) => ipcRenderer.invoke("painite:facebook-reload", profile),
  closeFacebook: (id) => ipcRenderer.invoke("painite:facebook-close", id),
  wipeFacebook: (id) => ipcRenderer.invoke("painite:wipe-profile", id),
  postMarketplace: (input) => ipcRenderer.invoke("painite:marketplace-post", input),
  showRent: (input) => ipcRenderer.invoke("painite:rent-show", input),
  hideRent: () => ipcRenderer.invoke("painite:rent-hide"),
  backRent: () => ipcRenderer.invoke("painite:rent-back"),
  reloadRent: () => ipcRenderer.invoke("painite:rent-reload"),
  clearRent: () => ipcRenderer.invoke("painite:rent-clear"),
  getStealthPath: () => ipcRenderer.invoke("painite:rent-stealth-path"),
  listingsRent: () => ipcRenderer.invoke("painite:rent-listings"),
  boundsRent: (bounds) => ipcRenderer.invoke("painite:rent-bounds", bounds),
  scrapeRent: () => ipcRenderer.invoke("painite:rent-scrape"),
  scrapeMessenger: () => ipcRenderer.invoke("painite:messenger-scrape"),
  sendMessenger: (text) => ipcRenderer.invoke("painite:messenger-send", text),
  robotStart: (input) => ipcRenderer.invoke("painite:robot-start", input),
  robotStop: (id) => ipcRenderer.invoke("painite:robot-stop", id),
  robotScrape: (id) => ipcRenderer.invoke("painite:robot-scrape", id),
  robotSend: (id, text) => ipcRenderer.invoke("painite:robot-send", { id, text }),
  robotSendPhotos: (id, images) => ipcRenderer.invoke("painite:robot-send-photos", { id, images }),
  robotOpenUnread: (id) => ipcRenderer.invoke("painite:robot-open-unread", id),
  captureInbox: (id) => ipcRenderer.invoke("painite:capture-inbox", id),
  checkFacebookLive: (id) => ipcRenderer.invoke("painite:fb-live-check", id),
  checkIp: (input) => ipcRenderer.invoke("painite:check-ip", input),
  copyText: (text) => ipcRenderer.invoke("painite:copy-text", text),
  uiReady: () => ipcRenderer.invoke("painite:ui-ready"),
  sessionGet: () => ipcRenderer.invoke("painite:session-get"),
  sessionSet: (data) => ipcRenderer.invoke("painite:session-set", data),
  postsGet: () => ipcRenderer.invoke("painite:posts-get"),
  postsSet: (rows) => ipcRenderer.invoke("painite:posts-set", rows),
});
